version: "3.9"

services:
  redis:
    image: redis:7-alpine

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      # Pointing DB_SOURCE to the host.docker.internal to connect with the local Postgres
      - DB_SOURCE=postgres://postgres:admin@host.docker.internal:5432/go_backend?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - redis
    entrypoint:
      [
        "/app/wait-for.sh",
        "host.docker.internal:5432",
        "--",
        "/app/start.sh"
      ]
    command: ["/app/main"]

volumes:
  data-volume:

    